### ISSUE TITLE
Can check the accessibility of YouTube embeds? Or other videos?

### ISSUE THREAD

**Issue by JenM00re** [Swarthmore/moodle-block_accessibility_filescan#15]
Be able to see if something has captions available or not and if so, whether they'd be auto generated v. human edited.

Not sure if an embed makes a difference as opposed to some upload.

Additionally, Panopto is used on our campus... so folks link out to there. May not be able to test accessibility when the link goes to something external to Moodle.

**Comment by devnoot** [comment]
This isn't the correct repo for this. Please create an issue on https://github.com/Swarthmore/moodle-local_accessibility_filescan/issues

This repo is only for the block. It doens't actually scan anything.
