### ISSUE TITLE
Link back to PDF in details view

### ISSUE THREAD

**Issue by ghost** [Swarthmore/moodle-block_accessibility_filescan#4]
When a user clicks on "Details" and is shown the details modal, they should be able to click on a filename to download the file directly.
![Screenshot_20230726_102859](https://github.com/aweed1/moodle-block_a11y_check/assets/139784904/47aa71d1-231f-4ba6-98d8-67eea858f095)

See the following image:

**Comment by devnoot** [comment]
This was fixed in a previous commit.

![image](https://github.com/Swarthmore/moodle-block_accessibility_filescan/assets/13612371/69b13677-70b5-44fe-9e5c-aaa6a46de90f)
