### ISSUE TITLE
Must scroll right for information

### ISSUE THREAD

**Issue by JenM00re** [Swarthmore/moodle-block_accessibility_filescan#6]
[Originally posted on the [moodle-local_a11y_check repo](https://github.com/Swarthmore/moodle-local_a11y_check/issues/53)] 
Can the pdf titles be wrapped so one doesn't have to scroll right for the checks, Xs, etc?

Or can the window and fields/table cells adjust to a user's screen size?

Or some other solution?
![Screenshot 2023-07-31 at 11 24 47 AM](https://github.com/aweed1/moodle-block_a11y_check/assets/91497451/0504769e-fcf9-4a73-8f28-763b599eaa2c)
List of files in A11y Check details page, scrolled left.

![Screenshot 2023-07-31 at 11 25 13 AM](https://github.com/aweed1/moodle-block_a11y_check/assets/91497451/88900639-aa3f-454e-9c1d-a3f412355f5a)
List of files in A11y Check details page, scrolled right, showing details.

**Comment by aruethe2** [comment]
Still an issue -- maybe related to Bootstrap class to truncate long filenames?

**Comment by devnoot** [comment]
This has been fixed in a previous commit.

![image](https://github.com/Swarthmore/moodle-block_accessibility_filescan/assets/13612371/0a9427a6-c590-4319-9986-748852106cf3)
