### ISSUE TITLE
CSV doesn't have column headings

### ISSUE THREAD

**Issue by JenM00re** [Swarthmore/moodle-block_accessibility_filescan#7]
The CSV that you can download does not have column headings.
<img width="939" alt=" " src="https://github.com/aweed1/moodle-block_a11y_check/assets/91497451/ab3a7515-8d15-47a8-9b62-ad171148a71b"> CSV of the A11y Check with no column headings.

**Comment by devnoot** [comment]
This was fixed at some point. Not sure which commit but it does return headings.

![image](https://github.com/Swarthmore/moodle-block_accessibility_filescan/assets/13612371/df35db5e-414d-4179-8add-2901b936e4ba)
