### ISSUE TITLE
Do not display the details button if there is no data

### ISSUE THREAD

**Issue by ghost** [Swarthmore/moodle-block_accessibility_filescan#9]
![Screenshot_20230803_134649](https://github.com/aweed1/moodle-block_a11y_check/assets/139784904/e49e8239-310d-4cae-a0c0-054f39c0dae7)

**Comment by devnoot** [comment]
Fixed in a previous commit.

![image](https://github.com/Swarthmore/moodle-block_accessibility_filescan/assets/13612371/aea7ceac-e01c-41b1-bafa-12e261dd90a3)
